version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    ports:
    - 9300:9300
    - 9200:9200
    environment:
    - discovery.type=single-node
    - cluster.routing.allocation.disk.watermark.flood_stage=99%
    - cluster.routing.allocation.disk.watermark.high=98%
    volumes:
    - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
