version: "3.7"
services:
  php:
    container_name: tainacan_fpm_apache
    image: tainacan/php:7.4-fpm-apache
    environment:
      SITE_URL: http://localhost
      APACHE_DOCUMENT_ROOT: "/var/www/html/public"
    ports:
      - "80:80"
      - "443:443"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.001'
    #       memory: 1000M
    volumes:
      - ./volumes/www:/var/www
      - ./volumes/src:/src
  mariadb:
    container_name: tainacan_db
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "tainacan"
      MARIADB_DATABASE: "tainacan"
      MARIADB_USER: "tainacan"
      MARIADB_PASSWORD: "tainacan"
    volumes:
      # Add volume for all database files
      - ./volumes/mysql/database_data/:/var/lib/mysql
      # Add volume for custom configurations
      - ./volumes/mysql/conf.d/:/etc/mysql/conf.d
      - ./volumes/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
