version: "3.3"

services:
 tainacan:
  image: tainacan/tainacan
  container_name: tainacan_${NAME_CONTAINER}
  ports:
     - "80"
     - "443"
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  volumes:
   - ${CNT_BASE_PATH}/${NAME_CONTAINER}/volumes/themes:/var/www/html/wp-content/themes/
   - ${CNT_BASE_PATH}/${NAME_CONTAINER}/volumes/plugins:/var/www/html/wp-content/plugins/
   - ${CNT_BASE_PATH}/${NAME_CONTAINER}/volumes/uploads:/var/www/html/wp-content/uploads/
   - ${FTP_DIR}:/ftp

 db:
  image: mysql:5.7
  #ports:
  #  - "3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  volumes:
  - ${CNT_BASE_PATH}/${NAME_CONTAINER}/data:/var/lib/mysql

volumes:
  wp_root:
